name: Download Github Folder

on:
  push:
    branches: main


jobs:
  github-folder-downloader:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: nodejs/node
        ref: v12.x
        path: node/doc
    - run: ls -a
    - run: ls /node
    - run: pwd && cd .. && pwd
    # - name: clone-git-repo
    
    #   run: git clone https://github.com/nodejs/node.git
    # - name: change-branch-and-dir
    #   run: git branch -a
    #   run: git checkout origin/v12.x && cd node/doc/
    # - name: move-api-to-home
    #   run: sudo mv api/ ~/ && cd ~
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: upload builds
    #     path: ./api
