name: Download Github Folder

on:
  push:
    branches: main


jobs:
  github-folder-downloader:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: clone-git-repo
      run: git clone https://github.com/nodejs/node.git
    - run: sudo chmod +x gitfolder.sh && sh gitfolder.sh
    - uses: actions/upload-artifact@v3
      with:
        name: upload builds
        path: ./api
