name: Download Github Folder

on:
  push:
    braches: main

jobs:
  github-folder-downloader:
    runson: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - run: git clone <url>
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: upload builds
    #     path: ./nameOfgitfolder e.g docs for npm packages 
