name: Show all files in current directory

on:
    push:
        branches:
            - main

jobs:
    print-files:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: pwd
        - run: mkdir -p artifact/
        - run: cd artifact && echo hello > world.txt && cd ..
        - uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: artifact/world.txt
