name: Show all files in current directory

on:
    push:
        branches:
            - main

jobs:
    print-files:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: mkdir news
        - run: help
