name: token checl
on:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: false

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest

    steps:
      - name: Pass the received secret to an 
        uses: ./github/workflows/main.yml
        with:
          token: ${{ secrets.access-token }}
      - run: echo "Test passed"
